### ISSUE TITLE
TODO list for PR#12 simplify module

### ISSUE THREAD

**Issue by kawanamiyuu** [ray-di/Ray.OAuthModule#13]
TODO list for #12 

- [x] refactor OAuth1 and OAuth2 Module
- [x] add DI trait sample
  - GoogleOAuthInject, GitHubOAuthInject
- [x] add `docs/demo/` sample
- [x] update README

**Comment by kawanamiyuu** [comment]
All done.

**Comment by koriym** [comment]
:+1:
